### ISSUE TITLE
Error Cordova

### ISSUE THREAD

**Issue by fuldev** [ToothlessGear/node-gcm#268]
hi i can't create a cordova project. please help me. the error:
Creating a new cordova project with name "HelloWorld" and id "helloworld.ubuntudeveloper" at location "/home/fuldev/helloworld"
Downloading cordova library for www...
Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND proxy proxy:8080
    at ClientRequest.onError (/usr/share/cordova-cli/node_modules/cordova-lib/node_modules/request/node_modules/tunnel-agent/index.js:176:17)
    at ClientRequest.g (events.js:260:16)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at Socket.socketErrorListener (_http_client.js:258:9)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at connectErrorNT (net.js:998:8)
    at nextTickCallbackWith2Args (node.js:441:9)
    at process._tickCallback (node.js:355:17)

**Comment by eladnava** [comment]
Hi @fuldev, how is this related to `node-gcm`?

**Comment by fuldev** [comment]
thank you.. i have already fixed the error. 
i delete the the proxy that i have used... and it works
